classDiagram
    User "0..1" o-- "0..*" ActivityLog
    User "1" *-- "0..*" Address
    Product3DModel "0..1" o-- "0..*" ArSession
    Product "1" -- "0..*" ArSession
    User "0..1" -- "0..*" ArSession
    ArSession "0..1" o-- "0..*" ArSnapshot
    Media "1" o-- "0..*" ArSnapshot
    Product "1" -- "0..*" ArSnapshot
    User "1" -- "0..*" ArSnapshot
    Attribute "1" *-- "0..*" AttributeValue
    Media "0..1" o-- "0..*" Brand
    Cart "1" *-- "0..*" CartItem
    ProductVariant "1" -- "0..*" CartItem
    User "1" *-- "0..1" Cart
    Media "0..1" o-- "0..*" Category
    Category "0..1" o-- "0..*" Category
    Coupon "1" o-- "0..*" CouponUsage
    Order "1" -- "0..*" CouponUsage
    User "1" o-- "0..*" CouponUsage
    User "0..1" o-- "0..*" InventoryMovement
    ProductVariant "1" o-- "0..*" InventoryMovement
    User "0..1" o-- "0..*" Media
    Media "1" o-- "0..*" ModelFile
    Product3DModel "1" *-- "0..*" ModelFile
    Product3DModel "1" *-- "0..*" ModelMaterialVariant
    ProductVariant "1" -- "0..*" ModelMaterialVariant
    User "1" *-- "0..*" Notification
    Order "1" *-- "1..*" OrderItem
    ProductVariant "0..1" o-- "0..*" OrderItem
    User "0..1" o-- "0..*" OrderStatusHistory
    Order "1" *-- "0..*" OrderStatusHistory
    Coupon "0..1" o-- "0..*" Order
    User "1" o-- "0..*" Order
    User "1" *-- "0..*" PasswordReset
    Order "1" o-- "0..*" Payment
    Media "0..1" o-- "0..*" Product3DModel
    Product "1" *-- "0..*" Product3DModel
    ProductVariant "1" -- "0..*" Product3DModel
    Media "1" o-- "0..*" ProductImage
    Product "1" *-- "0..*" ProductImage
    ProductVariant "1" -- "0..*" ProductImage
    Product "1" *-- "0..*" ProductVariant
    Brand "0..1" o-- "0..*" Product
    Category "0..1" o-- "0..*" Product
    Order "0..1" o-- "0..*" Review
    Product "1" -- "0..*" Review
    User "1" -- "0..*" Review
    Permission "1" *-- "0..*" RolePermission
    Role "1" *-- "0..*" RolePermission
    Order "1" o-- "0..*" Shipment
    Space "1" -- "0..*" SpaceBookmark
    User "1" -- "0..*" SpaceBookmark
    SpacePanorama "1" *-- "0..*" SpaceHotspot
    Product "0..1" -- "0..*" SpaceHotspot
    SpacePanorama "0..1" *-- "0..*" SpaceHotspot
    Media "1" o-- "0..*" SpacePanorama
    Space "1" *-- "0..*" SpacePanorama
    Product3DModel "0..1" o-- "0..*" SpaceProductPlacement
    SpacePanorama "1" *-- "0..*" SpaceProductPlacement
    Product "1" -- "0..*" SpaceProductPlacement
    ProductVariant "1" o-- "0..*" SpaceProductPlacement
    Product "0..1" o-- "0..*" SpaceView
    Space "1" -- "0..*" SpaceView
    User "0..1" -- "0..*" SpaceView
    Category "0..1" o-- "0..*" Space
    Media "0..1" o-- "0..*" Space
    Role "1" *-- "0..*" UserRole
    User "1" *-- "0..*" UserRole
    User "1" *-- "0..*" UserSession
    Media "0..1" o-- "0..*" User
    AttributeValue "1" *-- "0..*" VariantAttributeValue
    ProductVariant "1" *-- "0..*" VariantAttributeValue
    Product "1" -- "0..*" Wishlist
    User "1" -- "0..*" Wishlist
