// Mã lỗi nghiệp vụ dùng chung giữa API và web. Quy ước chi tiết: docs/API_CONVENTIONS.md (mục 4).
// Mỗi mã gắn với đúng một mã HTTP trong ERROR_HTTP_STATUS.

export const ErrorCode = {
  // 400
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  BAD_REQUEST: 'BAD_REQUEST',
  COUPON_INVALID: 'COUPON_INVALID',
  // 401
  AUTH_UNAUTHENTICATED: 'AUTH_UNAUTHENTICATED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  // 403
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  FORBIDDEN: 'FORBIDDEN',
  PURCHASE_REQUIRED: 'PURCHASE_REQUIRED',
  // 404
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  // 409
  CONFLICT: 'CONFLICT',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  INVALID_STATE: 'INVALID_STATE',
  RESOURCE_IN_USE: 'RESOURCE_IN_USE',
  // 413, 415, 429
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  RATE_LIMITED: 'RATE_LIMITED',
  // 5xx
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_GATEWAY: 'BAD_GATEWAY',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  VALIDATION_FAILED: 400,
  BAD_REQUEST: 400,
  COUPON_INVALID: 400,
  AUTH_UNAUTHENTICATED: 401,
  AUTH_INVALID_CREDENTIALS: 401,
  AUTH_TOKEN_EXPIRED: 401,
  AUTH_TOKEN_INVALID: 401,
  AUTH_ACCOUNT_LOCKED: 403,
  AUTH_EMAIL_NOT_VERIFIED: 403,
  FORBIDDEN: 403,
  PURCHASE_REQUIRED: 403,
  RESOURCE_NOT_FOUND: 404,
  CONFLICT: 409,
  EMAIL_ALREADY_EXISTS: 409,
  OUT_OF_STOCK: 409,
  INVALID_STATE: 409,
  RESOURCE_IN_USE: 409,
  PAYLOAD_TOO_LARGE: 413,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
};
