# Dockerfile build cho app web (Next.js)
FROM node:20-alpine AS base

WORKDIR /app
COPY apps/web/package.json ./apps/web/package.json
COPY package.json ./package.json

RUN npm install

COPY apps/web ./apps/web
COPY packages ./packages

WORKDIR /app/apps/web
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]
