# Dockerfile build cho app api (NestJS)
FROM node:20-alpine AS base

WORKDIR /app
COPY apps/api/package.json ./apps/api/package.json
COPY package.json ./package.json

RUN npm install

COPY apps/api ./apps/api
COPY packages ./packages

WORKDIR /app/apps/api
RUN npx prisma generate
RUN npm run build

EXPOSE 4000
CMD ["npm", "run", "start:prod"]
